server:
  port: 8501
spring:
  application:
    name: timeless-seckill-server
  datasource:
    url: jdbc:mysql://VirtualIP:3306/timeless_seckill?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: VirtualIP:8848
  rabbitmq:
    host: VirtualIP
    port: 5672
    username:
    password:
    virtual-host: /subtlechat
  profiles:
    active: dev
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # mybatis日志

alipay:
  returnUrl: http://8bcsm2.natappfree.cc/orderPay/returnUrl
  notifyUrl: http://8bcsm2.natappfree.cc/orderPay/notifyUrl

#feign:
#  hystrix:
#    enabled: true