server:
  port: 8501
spring:
  application:
    name: timeless-seckill-server
  datasource:
    url: jdbc:mysql://localhost:3306/timeless_seckill?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  rabbitmq:
    host: localhost # 192.168.111.100
    port: 5672
    username: guest # admin
    password: guest # 123

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # mybatis日志

alipay:
  returnUrl: http://rapwwc.natappfree.cc/orderPay/returnUrl
  notifyUrl: http://rapwwc.natappfree.cc/orderPay/notifyUrl