server:
  port: 8501
spring:
  application:
    name: timeless-seckill-server
  datasource:
    url: jdbc:mysql://你的虚拟机IP:3306/timeless_seckill?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 你的虚拟机IP:8848
  rabbitmq:
    host: 你的虚拟机IP
    port: 5672
    username: admin
    password:
    virtual-host: /subtlechat
  profiles:
    active: dev
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # mybatis日志

alipay:
  returnUrl: http://8bcsm2.natappfree.cc/orderPay/returnUrl
  notifyUrl: http://8bcsm2.natappfree.cc/orderPay/notifyUrl

feign:
  hystrix:
    enabled: true