# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER timeless

# 挂载目录
VOLUME /home/order
# 创建目录
RUN mkdir -p /home/order
# 指定路径
WORKDIR /home/order
# 复制jar文件到路径
COPY ./jar/timeless-pay-server.jar /home/order/timeless-pay-server.jar
# 启动用户服务
ENTRYPOINT ["java","-jar","timeless-pay-server.jar"]
